### PR TITLE
Typing corrections

### PR DESCRIPTION
**Pull request by andreagonzalez**
I made same corrections on pt-BR files

### CODE REVIEW

**Comment by neochief** [comment]
Hi Andrea!

I see a lot of the file mode changes in the commit. If you're on linux, can you go to your repository and run this to revert file modes to their original settings (without quotes) and then commit and push: "chmod -R 644 ." ?

**Comment by neochief** [comment]
There also some new pages in "es" subdirectory. If that's Spanish translation, could you please keep it in another branch?

**Comment by andreagonzalez** [comment]
> There also some new pages in "es" subdirectory. If that's Spanish translation, could you please keep it in another branch?

Hi, yes sorry it is a spanish translating that I am didn't finish yet, but I didn't want send yet. Sorry. I am learning about Git and don't have practice. I will fix it

**Comment by andreagonzalez** [comment]
> Hi Andrea!
> 
> I see a lot of the file mode changes in the commit. If you're on linux, can you go to your repository and run this to revert file modes to their original settings (without quotes) and then commit and push: "chmod -R 644 ." ?

Hi, yes sure... sorry I am just starting with git and github I will fix and send again

**Comment by neochief** [comment]
No worries, take your time.

**Comment by andreagonzalez** [comment]
Hi Alexander,

I think I can't do the changes. I don't know why but when I try change
permission of the directory I can't use git :-(
so I come back to chmod -r 777 and I can do the commits... Maybe you can
help me sending some place when I can understand more about you are telling
Really sorry, but I am not an advanced user

Em qua, 18 de set de 2019 às 15:11, Alexander Shvets <
notifications@github.com> escreveu:

**Comment by andreagonzalez** [comment]
> Hi Andrea!
> 
> I see a lot of the file mode changes in the commit. If you're on linux, can you go to your repository and run this to revert file modes to their original settings (without quotes) and then commit and push: "chmod -R 644 ." ?

I think I can't do the changes. I don't know why but when I try change permission of the directory I can't use git :-(
so I come back to chmod -r 777 and I can do the commits... Maybe you can help me sending some place when I can understand more about you are telling
Really sorry, but I am not an advanced user

**Comment by neochief** [comment]
No problem I've been fighting with this issue a lot back in the day.

Here's what I suggest you do:

1. Make a backup copy of your repository on your computer.

2. Delete your fork on GitHub. Note that after this, this pull request most likely will be gone, so copy this instruction somewhere. You'll create a new pull request on step 9.

3. Make a fresh fork on Github right after it.

4. Clone your fork into a new location on your computer.

5. Navigate to your newly cloned repository via command line and then run this (without quotes): "git config core.fileMode false" More info on this you can find here: https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes I also advice you run that command with a --global flag to prevent this from happening to other repositories in future.

6. Copy files from your backup over the files in your new repository. But make sure you're only copying the actual files and not the .git directory.

7. Once everything is carried over, you can check whether the file permissions are now ignored. Run "git diff" and see whether it contains only your changes to the files and not the file mode changes. Hopefully, it all should be okay.

8. If everything is okay, add and commit all of the changes.

9. Create a new pull request here.

**Pull request closed without merging**
